<?php /** @var \Magento\Framework\View\Element\Template $this */ ?>
<?php echo $block->getLayout()->getMessagesBlock()->getGroupedHtml(); ?>
<div class="kuWizardSteps">
<ol class="wizard-progress clearfix">
	<li class="active-step">
		<span class="step-name"><?php echo __("Register/Login");?></span>
		<span class="visuallyhidden"><?php echo __("Step");?> </span><span class="step-num">&nbsp;</span>
	</li>
	<li class="active-step">
		<span class="step-name"><?php echo __("Select Plan");?></span>
		<span class="visuallyhidden"><?php echo __("Step");?> </span><span class="step-num">&nbsp;</span>
	</li>
	<li class="active-step">
		<span class="step-name"><?php echo __("Configure Store");?></span>
		<span class="visuallyhidden"><?php echo __("Step");?></span><span class="step-num">&nbsp;</span>
	</li>
	<li class="active-step">
		<span class="step-name"><?php echo __("Finish & Sync");?></span>
		<span class="visuallyhidden"><?php echo __("Step");?> </span><span class="step-num">&nbsp;</span>
	</li>
</ol>
</div>

<div class="kuFinishSyncInfo">
	<h3><?php echo __('Please click the "Finish and Sync" button below to synchronise your products to Klevu.');?></h3>
	
	<ul>
		<li><?php echo __('Klevu Search will be automatically enabled on frontend after the first synchronisation completes.');?></li>
		<li><?php echo __('Data will be automatically resynchronised periodically as well as when any information changes.');?></li>
		<li><?php echo __('Make sure your CRON is setup.');?></li>
	</ul>
	
	<br/>
	<br/>
	<div class="button-set">
    <button id="sync-button" class="action-default primary"><span><?php echo __("Finish and Sync") ?></span></button><br/>
</div>
<h4 class="kuCompleteWarning"><?php echo __('Please do not close or refresh the page after clicking the button until the page has finished loading.');?></h4>
<script type="text/javascript">
require([
    "jquery",
    'Magento_Ui/js/modal/alert',
    "jquery/ui",
    "jquery/editableMultiselect/js/jquery.multiselect",
    "mage/mage",
    'Magento_Ui/js/modal/modal'
], function($, alert){
    $("#sync-button").on("click", function (e) {
        $('.loading-mask').show();
        window.location = "<?php echo $this->getUrl("klevu_search/manual/sync") ?>";
    });
});
</script>
</div>



