<?php /** @var \Klevu\Search\Block\Adminhtml\Form\Information $this */ ?>
<p><?php echo __("Installed Version: {$this->getVersion()}") ?></br></p>
<p><b><?php echo __("Prerequisites:") ?></b></br>
<?php echo __("1. Ensure cron is running > (<a href='http://www.klevu.com/support/setup-cron.html' target='_blank'>click here</a> for more information on setting up a cron)") ?></br>
<?php echo __("2. Indices are uptodate (System > Index Management)") ?></br>
<?php echo __("3. Products should be enabled and have the visibility set to catalog and search.") ?></p>
<p><b><?php echo __(" Klevu Merchant Centre: <a href='https://box.klevu.com' target='_blank'>https://box.klevu.com</a>");?></b></p>
<p><?php echo __("Once the Klevu Search is working on your website, login into Klevu Merchant Centre account to change look and feel of your search results, setup product promotions, see search activity, upgrade your account and lot more.");?></p>
<p><b><?php echo __("FAQs and Troubleshooting: <a href='http://www.klevu.com/support/support-home.html' target='_blank'>click here</a>");?></b></p>
<p><b><?php echo __("Migrating from staging to live: <a href='http://www.klevu.com/support/staging-to-live.html' target='_blank'>click here</a>");?></b></p>
