<?php $config = \Magento\Framework\App\ObjectManager::getInstance()->get('Klevu\Addtocart\Helper\Data'); ?>
<?php if ($config->isAddtocartEnabled()) {?>
<script type="text/javascript">
	function klevu_addtocart(id,url,qty) {
			var el = document.createElement("a");         
			el.setAttribute( "data-post", '{"action":"<?php echo $block->getUrl('checkout/cart/add');?>/product/'+id+'/","data":{"product":"'+id+'"}}' );    
			el.style.width="0px !important";
			el.style.height="0px !important";
			document.body.appendChild(el);
			el.click();
			document.body.removeChild(el);			
	}
</script>
<?php } ?>
