<?php /** @var \Klevu\Search\Block\Adminhtml\Form\Information $this */ ?>
<div class="kuInfo">
   <div class="kuInfo-fLeft">
      <p><b><?php echo __("Installed Version:") ?></b> <?php echo __("{$this->getVersion()}") ?></br></p>
      <?php $check_plan = \Magento\Framework\App\ObjectManager::getInstance()->get('Klevu\Search\Model\Product\Sync')->getFeatures();?>
      <?php if(empty($check_plan["errors"]) && !empty($check_plan)) { ?> 
        <p>
         <?php if(!empty($check_plan['user_plan_for_store'])) {?>
                <b><?php echo __("My Current Plan: ") ?></b>          
                <?php echo ucfirst($check_plan['user_plan_for_store']); 
         } ?> 
         <?php if(!empty($check_plan['upgrade_label'])) { ?>
             <button type='button' onClick=upgradeLink('<?php echo $check_plan["upgrade_url"]; ?>')><?php echo  $check_plan['upgrade_label']; ?></button>
             &nbsp;&nbsp;<a href="#" onClick="compareplan();"><?php echo __("Compare Plans"); ?></a>
         <?php } ?>  
        </p>
      <?php } ?>
   </div>
   <div class="kuInfo-fRight">
      <ul>
         <li><b>Quick Links:</b></li>
         <li><a target="_blank" href="http://support.klevu.com/knowledgebase/integration-steps-for-magento/"><?php echo __("Integration Steps");?></a></li>
         <li><a target="_blank" href="http://support.klevu.com/section/manuals/magento-manuals/migrate-klevu-search-from-staging-to-live/"><?php echo __("Migrating from Staging to Live");?></a></li>
         <li><a target="_blank" href="http://support.klevu.com/faq/faqs/how-to-upgrade-my-current-plan/"><?php echo __("How to upgrade plan?");?></a></li>
         <li><a target="_blank" href="http://box.klevu.com/"><?php echo __("Klevu Merchant Center");?></a></li>
      </ul>
   </div>
   <div class="kuInfoClear"></div>
</div>
<div>
   <p><b><?php echo __("Prerequisites:") ?></b></br>
      <?php echo __("1. Ensure cron is running (<a href='http://support.klevu.com/knowledgebase/setup-a-cron/' target='_blank'>Click here</a> for more information on setting up a cron)") ?></br>
      <?php echo __("2. Indices are uptodate (System > Index Management)") ?></br>
      <?php echo __("3. Products should be enabled and have the visibility set to catalog and search") ?>
   </p>
</div>