<?php /** @var \Klevu\Search\Block\Adminhtml\Notifications $this */ ?>
<?php $notifications = $this->getNotifications(); ?>
<?php foreach ($notifications as $notification): ?>
    <div class="klevu-notification notification-global">
        <strong><?php echo __("Klevu Search") ?>:</strong> [<?php echo $notification->getDate() ?>] <?php echo $notification->getMessage() ?>
        <a class="dismiss" href="<?php echo $this->getDismissUrl($notification) ?>"><?php echo __("Dismiss") ?></a>
    </div>
<?php endforeach; ?>
